#version 450
 
layout (binding = 0, rgba8) uniform readonly image2D renderTexture;

layout (binding = 1, rgba8) uniform writeonly image2D targetTexture;


layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
	ivec2 pixelCoords = ivec2(gl_LocalInvocationID.xy) + 1 * ivec2(gl_WorkGroupID.xy);

	vec4 pixel = imageLoad(renderTexture, pixelCoords).rgba;

	imageStore(targetTexture, pixelCoords, pixel);
}